### ISSUE TITLE
Choosing a naming convention

### ISSUE THREAD

**Issue by LoupVaillant** [cphrn/monocypher#1]
There is a practice in Haskell that exhorts library writers to name their identifiers for qualified usage. Users can then shorten the name of the namespace with the `import qualified` declaration.

Rust can do the same, and I feel you are not taking full advantage.

For instance, there is a good deal of redundancy in the `monocypher::crypto_lock::lock` function name. In the C library, the `crypto_` prefix was used as a namespace. Since you already have the `monocypher`, "crypto" is now redundant. Then there's the repetition of "lock" in the fully qualified name (though I understand the reasons there).

It is as if you expected your users to `use monocypher` and pollute their global namespace with all monocypher's identifiers. As a user, I prefer to do something like this:

    use monocypher as crypto;
    use monocypher as m;     // or maybe that

That way I have my shortcut, without any risk of name clash.

So, how about changing this:

    pub mod blake2;
    pub mod crypto_lock;
    pub mod crypto_unlock;
    pub mod crypto_sign;
    pub mod crypto_check;
    pub mod crypto_utils;

to that?

    pub mod blake2;
    pub mod lock;
    pub mod unlock;
    pub mod sign;
    pub mod check;
    pub mod utils;

In the same vein, I love what you've done with contexes (I would have done the same), but how about replacing stuff like this:

    impl CryptoLockCtx {

by that:

    impl Context {

(Note: "context" may not be the best name either. If you come up with something more informative, you may want to use that instead.)

You don't need the terseness of "ctx" thanks to the namespaces (users can shorter the names as they see fit), and you don't need to repeat "crypto" (redundant with "monocypher") or "lock" (redundant with the name of the module). Thus, a user who wants to use the incremental encryption interface would do something like this:

    use monocypher as crypto;
    let mut lockCtx = crypto::lock::context {
        key  : myKey,
        nonce: myNonce,
    };
    lockCtx.auth_ad();
    lockCtx.auth_message();
    lockCtx.update();
    // etc

(You may have noticed by now that I don't know Rust.)

---

Then there's the separate issue of a second-level namespace. It wouldn't be my first choice. I'd lump everything in `monocypher` without a second thought, and just strip the `crypto_` prefix from everything. Simple, brutish, matches the name of the C library perfectly, but perhaps not what you were looking for.

Assuming you do want that second level, I suggest you depart from Monocypher's original naming a bit.

Almost all primitives come with a monolithic interface, and an incremental interface. The monolithic interface is named after its own namespace. `lock` in particular has the `lock()` function, and the `aead_lock()` (which really should be `lock_aead()`, if you care to follow my latest naming convention). Problem is, "lock" is redundant. May I suggest that you rename them `easy()` and `aead()` respectively? That way you would have the following fully qualified names:

    monocypher::lock::easy
    monocypher::lock::aead
    monocypher::lock::context

The same can be done to the others:

    monocypher::blake2b::easy
    monocypher::blake2b::general
    monocypher::blake2b::context

    monocypher::argon2i::easy
    monocypher::argon2i::general

    monocypher::poly1305::auth
    monocypher::poly1305::context

Etc.

That was a big one, but I hope that will help you decide how you want to proceed.

**Comment by jan-schreib** [comment]
First I have to say I really like your suggestion, thank you for that. I had quite a hard time naming the functions and how to structure the files. (Naming things really is hard.)
I was always a fan of naming the easy things "easy". I'm very happy that you suggested that. E.g. Curl does something similar with the curl_easy_* family. I'll work something out and open up a pull request so you can have another look. One reason for me not publishing it on crates.io where things like that.

Thanks again for you work and suggestions!

**Comment by jan-schreib** [comment]
I liked your suggestions so much, that I implemented them directly in 13f739e
Have a look if you have time.

**Comment by LoupVaillant** [comment]
Well, I've looked, and that's pretty much perfect. This issue is as good as solved as far as I am concerned. I'm closing this, good work.

I do have 3 very minor bike shedding nitpicks. I'm not even sure they're worth modifying anything, but in case you're interested, here goes:

* I noticed you used "finish" instead of "final". While arguably a better name (it's a verb like "init" and "update"), all libraries I have seen have settled on "final", and I saw no strong reason to break that expectation. Speaking of which, the Rust community may or may not have a rough consensus on streaming interfaces already. You might want to look for hash or checksum implementations in Rust, see how they named their stuff.

* Replacing "init" by constructors is good. There is one left however: `crypto::sign::init_second_pass`. Since nothing is called "init" any more, you have more freedom over this name. You may or may not prefer `begin_second_pass`, or even something else I haven't thought about. On the other hand, not deviating from the original name might help those who read _my_ documentation to use your bindings.

* You now have `crypto::poly1305::easy`. While "easy" maximises consistency with the rest of your bindings, the only thing easy about Poly1305 is making mistakes. Plus, there is no general counterpart like there is with Blake2b, Argon2i, and lock/unlock. Hence my initial "auth" suggestion. Tough choice: do you want consistency ("easy"), or do you want to avoid giving the wrong impression ("auth"). I *think* I'd favour consistency, but I'm still torn.

**Comment by jan-schreib** [comment]
> I noticed you used "finish" instead of "final".

Final is a reserved keywort in Rust. I looked at the OpenSSL bindings and they use finalize. I will change it to that.

> There is one left however: crypto::sign::init_second_pass. Since nothing is called "init" any more, you have more freedom over this name. 

Thanks for that one, I missed it. Your suggestion is perfect!

I was thinking about your third point. I dont think there is wrong or right here. Although its easy to use Poly1305 with my bindings to your function, its seems like its way easier to reuse the mac. Your naming is on point again. You can not imagine how much I appreciate your help!
